# **AIN 214 - PA1 - FALL 2025**

**Student ID** : 2230765032

**Name-Surname**   : Baki Umut Gündüz

**Deadline: 3.11.2025 (23:59:59)**

**Submission:** Submit your Jupyter Notebooks via https://submit.cs.hacettepe.edu.tr/

# **Necessary Imports**

In [1]:
# Import required libraries
import pandas as pd
import sqlite3

# **Notes:**

* Use pandas dataframe (df) to load the data.

* Use numpy or pandas operations for the requested tasks unless otherwise specified.

* You can insert more cells if it is necessary.

# **PART 1: Flight Delays and Cancellations Dataset**

The US Department of Transportation's Bureau of Transportation.

**Dataset Path: "datasets/flights_dataset/*.csv"**

- `flights.csv` contains the flight information

| Variable   | Description                                          |
|------------|------------------------------------------------------|
| `year`, `month`, `day` | The time information of the flight |
| `dep_time`   | Departure time (in the format hhmm) where`NA` corresponds to a cancelled flight        |
| `sched_dep_time`    | Scheduled departure time                        |
| `dep_delay`  | Departure delay, in minutes (negative for early)    |
| `arr_time`  | Arrival time    |
| `sched_arr_time`  | Scheduled arrival time    |
| `arr_delay`  | Arrival delay, in minutes (negative for early)    |
| `carrier`  | Carrier/airline code    |
| `tailnum`  | Tail number of the plane    |
| `origin`     | Origin airport where flight starts (IATA code)
| `airline`    | Carrier/airline name                        |
| `dest`       | Destination airport where flight lands (IATA code)  |
| `air_time`    | The duration of flight (on air)                       |
| `distance`    | The distance between origin and destination airports (miles)                        |
| `hour`, `minute`, `time_hour`    | Time information of the flight                       

- `flights_weather.csv` contains the same flight information as well as weather conditions such as

| Variable   | Description                                           |
|------------|-------------------------------------------------------|
| `visib`      | Visibility (in miles)                                 |
| `wind_gust`  | Wind gust speed (in mph)

### Load & Inspect the Data (15 pts)

Load `flights.csv` as `flights_df` and `flights_weather.csv` as `weather_df` by using pandas DataFrame. (2 pts)

In [2]:
# Load the data
flights_df = pd.read_csv("datasets/flights_dataset/flights.csv")
weather_df = pd.read_csv("datasets/flights_dataset/flights_weather.csv")

Show the first and the last five rows of the datasets. (4 pts)

In [3]:
# flights_df
flights_df.head()

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour,airline
0,2022,1,1,1.0,2359,2.0,604.0,618,-14.0,UA,555,N405UA,SEA,IAH,221.0,1874,23,59,2022-01-01T23:00:00Z,United Air Lines Inc.
1,2022,1,1,1.0,2250,71.0,242.0,142,60.0,AS,72,N265AK,SEA,FAI,193.0,1533,22,50,2022-01-01T22:00:00Z,Alaska Airlines Inc.
2,2022,1,1,10.0,2355,15.0,759.0,730,29.0,AS,270,N274AK,SEA,ATL,261.0,2182,23,55,2022-01-01T23:00:00Z,Alaska Airlines Inc.
3,2022,1,1,25.0,2350,35.0,606.0,550,16.0,AS,7,N281AK,SEA,ORD,193.0,1721,23,50,2022-01-01T23:00:00Z,Alaska Airlines Inc.
4,2022,1,1,35.0,2349,46.0,616.0,545,31.0,UA,507,N426UA,PDX,ORD,196.0,1739,23,49,2022-01-01T23:00:00Z,United Air Lines Inc.

In [4]:
flights_df.tail()

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour,airline
111371,2022,6,30,NaN,1155,NaN,NaN,2033,NaN,UA,206,NaN,SEA,EWR,NaN,2402,11,55,2022-06-30T11:00:00Z,United Air Lines Inc.
111372,2022,6,30,NaN,1448,NaN,NaN,1732,NaN,DL,323,N3759,SEA,LAX,NaN,954,14,48,2022-06-30T14:00:00Z,Delta Air Lines Inc.
111373,2022,6,30,NaN,1751,NaN,NaN,2352,NaN,DL,377,N898DN,SEA,ORD,NaN,1721,17,51,2022-06-30T17:00:00Z,Delta Air Lines Inc.
111374,2022,6,30,NaN,1145,NaN,NaN,2029,NaN,DL,114,N876DN,SEA,JFK,NaN,2422,11,45,2022-06-30T11:00:00Z,Delta Air Lines Inc.
111375,2022,6,30,NaN,720,NaN,NaN,1544,NaN,DL,168,N814DN,SEA,BOS,NaN,2496,7,20,2022-06-30T07:00:00Z,Delta Air Lines Inc.

In [5]:
# weather
weather_df.head()

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,...,route,temp,dewp,humid,wind_dir,wind_speed,wind_gust,precip,pressure,visib
0,2022,1,1,1.0,2359,2.0,604.0,618,-14.0,UA,...,SEA-IAH,33.0,23.0,66.06,160.0,8.05546,9.270062,0.0,1022.9,10.0
1,2022,1,1,1.0,2250,71.0,242.0,142,60.0,AS,...,SEA-FAI,32.0,23.0,69.04,170.0,9.20624,10.594357,0.0,1023.4,10.0
2,2022,1,1,10.0,2355,15.0,759.0,730,29.0,AS,...,SEA-ATL,33.0,23.0,66.06,160.0,8.05546,9.270062,0.0,1022.9,10.0
3,2022,1,1,25.0,2350,35.0,606.0,550,16.0,AS,...,SEA-ORD,33.0,23.0,66.06,160.0,8.05546,9.270062,0.0,1022.9,10.0
4,2022,1,1,35.0,2349,46.0,616.0,545,31.0,UA,...,PDX-ORD,33.0,19.0,55.75,120.0,6.90468,7.945768,0.0,1025.1,10.0

In [6]:
weather_df.tail()

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,...,route,temp,dewp,humid,wind_dir,wind_speed,wind_gust,precip,pressure,visib
111001,2022,6,30,NaN,1155,NaN,NaN,2033,NaN,UA,...,SEA-EWR,56.0,51.0,83.88,30.0,9.20624,10.594357,0.0,1021.5,10.0
111002,2022,6,30,NaN,1448,NaN,NaN,1732,NaN,DL,...,SEA-LAX,60.0,53.0,77.65,20.0,6.90468,7.945768,0.0,1021.9,10.0
111003,2022,6,30,NaN,1751,NaN,NaN,2352,NaN,DL,...,SEA-ORD,65.0,53.0,65.56,280.0,6.90468,7.945768,0.0,1021.3,10.0
111004,2022,6,30,NaN,1145,NaN,NaN,2029,NaN,DL,...,SEA-JFK,56.0,51.0,83.88,30.0,9.20624,10.594357,0.0,1021.5,10.0
111005,2022,6,30,NaN,720,NaN,NaN,1544,NaN,DL,...,SEA-BOS,56.0,50.0,80.52,350.0,5.75390,6.621473,0.0,1021.8,10.0

How many records(rows) exists on each dataset? Use print function for the answer. (2 pts)

In [7]:
# Show the number of records (rows) in each dataset.
print(flights_df.shape[0])
print(weather_df.shape[0])

111376
111006

What are the column types? Print columns and their datatypes. (2 pts)

In [8]:
# Show the data types for columns
print(flights_df.dtypes)

year                int64
month               int64
day                 int64
dep_time          float64
sched_dep_time      int64
dep_delay         float64
arr_time          float64
sched_arr_time      int64
arr_delay         float64
carrier            object
flight              int64
tailnum            object
origin             object
dest               object
air_time          float64
distance            int64
hour                int64
minute              int64
time_hour          object
airline            object
dtype: object

Compute a missing value summary (count and %) per column for each dataset. (3 pts)

In [9]:
# Print the summary
def findMissingValuePercent(dataframe):
    missing_values = dataframe.isnull().sum()
    missing_values_percent = missing_values / len(dataframe) * 100
    print(missing_values_percent)

findMissingValuePercent(flights_df)

year              0.000000
month             0.000000
day               0.000000
dep_time          2.195266
sched_dep_time    0.000000
dep_delay         2.195266
arr_time          2.282359
sched_arr_time    0.000000
arr_delay         2.405366
carrier           0.000000
flight            0.000000
tailnum           0.115824
origin            0.000000
dest              0.000000
air_time          2.405366
distance          0.000000
hour              0.000000
minute            0.000000
time_hour         0.000000
airline           0.000000
dtype: float64

In [10]:
findMissingValuePercent(weather_df)

year              0.000000
month             0.000000
day               0.000000
dep_time          2.198079
sched_dep_time    0.000000
dep_delay         2.198079
arr_time          2.285462
sched_arr_time    0.000000
arr_delay         2.408879
carrier           0.000000
flight            0.000000
tailnum           0.116210
origin            0.000000
dest              0.000000
air_time          2.408879
distance          0.000000
hour              0.000000
minute            0.000000
airline           0.000000
route             0.000000
temp              0.000000
dewp              0.000000
humid             0.000000
wind_dir          2.849396
wind_speed        0.251338
wind_gust         0.251338
precip            0.000000
pressure          0.000000
visib             0.000000
dtype: float64

Identify likely key columns for a potential merging between two datasets. (2 pts)

In [11]:
# Answer here
"The likely key columns for merging the two datasets are year, month, day, hour, minute, and flight, since these variables together can uniquely identify each flight at a specific time."

'The likely key columns for merging the two datasets are year, month, day, hour, minute, and flight, since these variables together can uniquely identify each flight at a specific time.'

### Data Exploration and Analysis (35 pts)

**Note:** You can create new columns, merge datasets or perform any other operations in this stage.

How many different airlines has flight records in the flights dataset? (2 pts)

In [12]:
# Answer the question above
flights_df["airline"].unique().shape[0]

12

Calculate the mean, min, max and std of the departure delay times. (Column: `dep_delay`) (2 pts)

In [13]:
# Answer the question above
print(flights_df["dep_delay"].agg(["mean", "max", "min", "std"]))

mean       8.036675
max     2120.000000
min      -36.000000
std       41.651032
Name: dep_delay, dtype: float64

Compute the summary statistics for weather columns. (`temperature`, `wind_speed`, `precipitation`) (2 pts)

In [14]:
# Answer the question above
weather_df[["temp", "wind_speed", "precip"]].describe()

                temp     wind_speed         precip
count  111006.000000  110727.000000  111006.000000
mean       48.155538       6.995307       0.005774
std         9.363201       4.507431       0.022099
min        21.900000       0.000000       0.000000
25%        42.000000       4.603120       0.000000
50%        47.000000       6.904680       0.000000
75%        54.000000       9.206240       0.000000
max        99.000000      27.618720       0.320000

How many flights are delayed more than 15 minutes? Report count and the percentage. (3 pts)

In [15]:
# Answer the question above
count = flights_df[flights_df["dep_delay"] > 15].shape[0]
percentage = count / flights_df["dep_delay"].shape[0] * 100
print(count, round(percentage, 3))

17539 15.748

How many flights are cancelled in the dataset? (3 pts)

In [16]:
# Answer the question above
cancelled_flights = flights_df[flights_df["dep_time"].isna()]
len(cancelled_flights)

2445

Report top 5 airlines has the most cancellation by count and percantage seperately. (3 pts)

In [17]:
# Answer the question above
top5_cancel_count = cancelled_flights["airline"].value_counts().head()
top5_cancel_count

airline
Alaska Airlines Inc.      1300
Delta Air Lines Inc.       383
Horizon Air                238
SkyWest Airlines Inc.      165
Southwest Airlines Co.     100
Name: count, dtype: int64

Which airline has the highest departure delay average? And what is the average delay for the airline? (3 pts)

In [18]:
# Answer the question above
avg_delay = flights_df.groupby("airline")["dep_delay"].mean().sort_values(ascending=False)
highest_airline = avg_delay.idxmax()
highest_value = avg_delay.max()
print(highest_airline)
print(highest_value)

JetBlue Airways
42.14152410575428

Which routes has the most cancelled flights? Report top 10 routes and the number of cancelled flights. (Note: A route is "[origin]-[dest]". For example PDX-BUR) (4 pts)

In [19]:
# Answer the question above
cancelled = flights_df[flights_df["dep_time"].isna()].copy()
cancelled["route"] = cancelled["origin"].str.strip() + "-" + cancelled["dest"].str.strip()

top10_routes = cancelled["route"].value_counts().head(10)
top10_routes

route
SEA-LAX    93
SEA-ANC    78
SEA-LAS    73
SEA-SFO    73
SEA-PDX    71
SEA-JFK    70
PDX-SEA    68
SEA-DEN    66
SEA-ORD    63
SEA-PHX    60
Name: count, dtype: int64

Which route has the highest average departure delay time? Report top 10 routes with the average departure delay times. (3 pts)

In [20]:
# Answer the question above
flights_copy = flights_df.copy()
flights_copy["route"] = (flights_copy["origin"].str.strip() + "-" + flights_copy["dest"].str.strip())
valid_flights = flights_copy.groupby("route")["dep_delay"].mean().sort_values(ascending=False)

print(valid_flights.idxmax())
print(valid_flights.head(10))

PDX-DSM
route
PDX-DSM    35.782609
PDX-GRR    35.739130
PDX-FLL    30.893617
SEA-MIA    29.916667
SEA-CLT    27.313199
PDX-STL    27.000000
PDX-BOS    24.812500
PDX-DFW    24.735941
PDX-DAL    24.100000
PDX-JFK    21.729433
Name: dep_delay, dtype: float64

Compare mean departure delay between rainy and non-rainy flights. (5 pts)

Tip: Check `precip` column in weather dataset

In [21]:
# Answer the question above
rainy = weather_df[weather_df["precip"] > 0]["dep_delay"].mean()
non_rainy = weather_df[weather_df["precip"] == 0]["dep_delay"].mean()
print(rainy)
print(non_rainy)

10.030634573304157
7.424000289247234

Compare mean departure delay between wind condition. Consider 10 mile per hour or more wind gust is considered as windy. (5 pts)

In [22]:
# Answer the question above
wind_delay = weather_df[weather_df["wind_gust"] > 10]["dep_delay"].mean()
print(wind_delay)

9.216318104299434

# **PART- 2**

**SQL Questions**

**You must use sqlite3 library for SQL operations**

**Dataset Url: https://www.kaggle.com/datasets/ayeshaimran123/foodpanda-order-and-delivery-trends**


The Foodpanda Order & Delivery Trends dataset contains information about customer orders made through the Foodpanda application. It includes details such as customer information, order status, restaurant data, ratings, payment methods, and more.

Dataset description

# Tables

## 1. Customer Table

| Column          | Type    | Key         | Description                                                                                              |
|-----------------|---------|-------------|----------------------------------------------------------------------------------------------------------|
| customer_id     | TEXT    | PRIMARY KEY | Unique identifier for each customer                                                                      |
| gender          | TEXT    |             | Gender of the customer                                                                                   |
| age_group       | TEXT    |             | Categorizes customers into broad age-based segments                                                      |
| city            | TEXT    |             | Indicates the city where customer resides                                                                |
| signup_date     | TEXT    |             | Represents the date when the customers created their account on Foodpanda platform                       |
| order_frequency | INTEGER |             | nIdicates how frequently customer places orders                                                          |
| last_order_date | TEXT    |             | Date of last order                                                                                       |
| loyalty_points  | INTEGER |             | Represents the reward points earned by a customer                                                        |
| churned         | TEXT    |             | nIdicates whether customer has stopped using the Foodpanda platform after a certain period of inactivity |



## 2. Order Table

| Column          | Type    | Key     | Description                                                                                                                                                |
| --------------- | ------- | ------- | ---------------------------------------------------------------------------------------------------------------------------------------------------------- |
| order_id        | TEXT    | PRIMARY | Unique identifier for orders                                                                                                                               |
| customer_id     | TEXT    | FOREIGN | Unique identifier for customers                                                                                                                            |
| restaurant_id   | INTEGER | FOREIGN | Unique identifier for restaurants                                                                                                                          |
| order_date      | TEXT    |         | Date of order                                                                                                                                              |
| dish_name       | TEXT    |         | Indicates the type of the food item ordered by the customer                                                                                                |
| category        | TEXT    |         | Represents the cusine of the ordered dish                                                                                                                  |
| quantity        | INTEGER |         | Indicates the number of units of a particular dish ordered by the customer in a single order                                                               |
| price           | REAL    |         | Represents the total cost of the ordered dish                                                                                                              |
| payment_method  | TEXT    |         | Specifies the method used by the customer to pay for the order                                                                                             |
| rating          | INTEGER |         | Indicates the numerical rating (usually on a scale such as 1–5) given by the customer to evaluate their satisfaction with the order or delivery experience |
| rating_date     | TEXT    |         | Represents the date when the customer submitted their rating or review for the order                                                                       |
| delivery_status | TEXT    |         | Describes the final status of the order’s delivery process                                                                                                 |


## 3. Restaurant Table

| Column          | Type    | Key     | Description                        |
|-----------------|---------|---------|------------------------------------|
| restaurant_id   | INTEGER | PRIMARY | Unique indetifiers for restaurants |
| restaurant_name | TEXT    |         | Name of the restaurant             |

**Dataset path: Data/Foodpanda Analysis Dataset.csv**

In this section, you will work with the Foodpanda Order & Delivery Trends dataset, which stores information about orders made on the Foodpanda platform. You are required to read the dataset from a CSV file, build a relational database, and write code to answer the following questions. When creating the database, you must follow the table schema described above.

# Questions (50p)

1. Read the csv file and create database. (10p)
2. Find the top 3 restaurants with the highest total revenue. (revenue = quantity x price) (5p)
3. Calculate the total quantity of dishes sold by category for each restaurant. (5p)
4. List the top 5 customer with highest total spending (also show total spending value) (5p)
5. Find the average rating for each restaurant. (5p)
6. Check for duplicate orders (same customer_id+restaurant_id+order_date). (5p)
7. Find the percentage of orders by delivery status. (7p)
8. Analyze whether specific cities contribute a significantly larger portion to the total revenue compared to others. (8p)

In [23]:
df = pd.read_csv("Data/Foodpanda Analysis Dataset.csv")

df["restaurant_id"] = df["restaurant_name"].factorize()[0] + 1

conn = sqlite3.connect(":memory:")

conn.executescript("""
DROP TABLE IF EXISTS Customer;
DROP TABLE IF EXISTS Restaurant;
DROP TABLE IF EXISTS Orders;

CREATE TABLE Customer (
    customer_id TEXT PRIMARY KEY,
    gender TEXT,
    age TEXT,
    city TEXT,
    signup_date TEXT,
    order_frequency INTEGER,
    last_order_date TEXT,
    loyalty_points INTEGER,
    churned TEXT
);

CREATE TABLE Restaurant (
    restaurant_id INTEGER PRIMARY KEY,
    restaurant_name TEXT
);

CREATE TABLE Orders (
    order_id TEXT PRIMARY KEY,
    customer_id TEXT,
    restaurant_id INTEGER,
    order_date TEXT,
    dish_name TEXT,
    category TEXT,
    quantity INTEGER,
    price REAL,
    payment_method TEXT,
    rating INTEGER,
    rating_date TEXT,
    delivery_status TEXT,
    FOREIGN KEY (customer_id) REFERENCES Customer(customer_id),
    FOREIGN KEY (restaurant_id) REFERENCES Restaurant(restaurant_id)
);
""")

df_customers = df[[
    "customer_id", "gender", "age", "city", "signup_date",
    "order_frequency", "last_order_date", "loyalty_points", "churned"
]].drop_duplicates(subset=["customer_id"])

df_restaurants = df[["restaurant_id", "restaurant_name"]].drop_duplicates(subset=["restaurant_id"])

df_orders = df[[
    "order_id", "customer_id", "restaurant_id", "order_date", "dish_name",
    "category", "quantity", "price", "payment_method",
    "rating", "rating_date", "delivery_status"
]]

df_customers.to_sql("Customer", conn, if_exists="append", index=False)
df_restaurants.to_sql("Restaurant", conn, if_exists="append", index=False)
df_orders.to_sql("Orders", conn, if_exists="append", index=False);

In [24]:
#2
query = """
SELECT R.restaurant_name, SUM(O.quantity * O.price) AS total_revenue FROM Orders AS O
JOIN Restaurant AS R ON O.restaurant_id = R.restaurant_id
GROUP BY R.restaurant_id
ORDER BY total_revenue DESC
LIMIT 3;
"""

df_result = pd.read_sql_query(query, conn)
print(df_result)

  restaurant_name  total_revenue
0       Pizza Hut     3002380.59
1          Subway     2998014.27
2             KFC     2954233.45

In [25]:
#3
query = """
SELECT R.restaurant_name, O.category, SUM(O.quantity) AS total_quantity FROM Orders AS O
JOIN Restaurant AS R ON O.restaurant_id = R.restaurant_id
GROUP BY R.restaurant_name, O.category
ORDER BY R.restaurant_name, total_quantity DESC;
"""

df_result = pd.read_sql_query(query, conn)
print(df_result)

   restaurant_name     category  total_quantity
0      Burger King    Fast Food             799
1      Burger King  Continental             689
2      Burger King      Italian             681
3      Burger King      Dessert             658
4      Burger King      Chinese             649
5              KFC  Continental             757
6              KFC      Chinese             754
7              KFC    Fast Food             747
8              KFC      Italian             735
9              KFC      Dessert             641
10      McDonald's      Italian             699
11      McDonald's    Fast Food             686
12      McDonald's  Continental             665
13      McDonald's      Chinese             658
14      McDonald's      Dessert             651
15       Pizza Hut  Continental             803
16       Pizza Hut      Chinese             801
17       Pizza Hut      Dessert             746
18       Pizza Hut      Italian             738
19       Pizza Hut    Fast Food             638
20          Subway      Italian             859
21          Subway    Fast Food             746
22          Subway  Continental             730
23          Subway      Dessert             715
24          Subway      Chinese             705

In [26]:
#4
query = """
SELECT C.customer_id, SUM(O.price) AS total_spending FROM Orders AS O
JOIN Customer AS C ON O.customer_id = C.customer_id
GROUP BY C.customer_id
ORDER BY total_spending DESC
LIMIT 5;
"""

df_result = pd.read_sql_query(query, conn)
print(df_result)

  customer_id  total_spending
0       C1227         1499.95
1       C5781         1499.73
2       C5825         1499.68
3       C4114         1499.59
4       C3134         1499.37

In [27]:
#5
query = """
SELECT R.restaurant_name, AVG(O.rating) AS average_rating FROM Orders AS O
JOIN Restaurant AS R ON O.restaurant_id = R.restaurant_id
GROUP BY R.restaurant_id
ORDER BY average_rating DESC;
"""

df_result = pd.read_sql_query(query, conn)
print(df_result)

  restaurant_name  average_rating
0          Subway        3.087302
1      McDonald's        3.002629
2             KFC        2.974673
3     Burger King        2.966116
4       Pizza Hut        2.949346

In [28]:
#6
query = """
SELECT customer_id, restaurant_id, order_date, COUNT(*) AS tekrar_sayisi FROM Orders
GROUP BY customer_id, restaurant_id, order_date
HAVING COUNT(*) > 1;
"""

df_result = pd.read_sql_query(query, conn)
print(df_result)

Empty DataFrame
Columns: [customer_id, restaurant_id, order_date, tekrar_sayisi]
Index: []

In [29]:
#7
query = """
SELECT delivery_status, COUNT(*) * 100.0 / (SELECT COUNT(*) FROM Orders) AS percentage FROM Orders
GROUP BY delivery_status
ORDER BY percentage DESC;
"""

df_result = pd.read_sql_query(query, conn)
print(df_result)

  delivery_status  percentage
0       Delivered   34.333333
1         Delayed   32.866667
2       Cancelled   32.800000

In [30]:
#8
query = """
SELECT C.city, SUM(O.quantity * O.price) AS total_revenue, ROUND(SUM(O.quantity * O.price) * 100.0 /
(SELECT SUM(quantity * price) FROM Orders), 2) AS percentage_of_total
FROM Customer AS C
JOIN Orders AS O ON O.customer_id = C.customer_id
GROUP BY C.city
ORDER BY total_revenue DESC;
"""

df_result = pd.read_sql_query(query, conn)
print(df_result)

        city  total_revenue  percentage_of_total
0     Multan     3052313.80                21.28
1     Lahore     2916372.35                20.33
2   Peshawar     2906686.38                20.26
3  Islamabad     2835310.27                19.77
4    Karachi     2633229.28                18.36

In [31]:
conn.close()

# PLAGIARISM

All work on assignments must be done individually. You are encouraged to discuss the given assignments with your classmates, but these discussions should be carried out in an abstract way. That is, discussions related to a particular solution to a specific probem (either in actual code or in pseudocode) will not be tolerated. In short, turning in someone else’s work (including work available on the internet), in whole or in part, as your own will be considered as a violation of academic integrity. Please note that the former conditions also hold for the material attained using AI tools, including ChatGPT, GitHub Copilot, etc.